# Generated by Django 3.0.2 on 2020-05-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameFileDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=512, null=True)),
                ('available', models.BooleanField(default=False)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('update_data', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'game_file_db',
            },
        ),
    ]
